export const APPOINTMENT_TYPE = {
  ONLINE: "online",
  PRESENCIAL: "presencial",
};

export const APPOINTMENT_TYPE_MODE = {
  DISABLED: "disabled",
  FIXED: "fixed",
  CHOICE: "choice",
};

export const APPOINTMENT_TYPE_LABELS = {
  [APPOINTMENT_TYPE.ONLINE]: "Online",
  [APPOINTMENT_TYPE.PRESENCIAL]: "Presencial",
};

export const APPOINTMENT_TYPE_MODE_LABELS = {
  [APPOINTMENT_TYPE_MODE.DISABLED]: "Desabilitado",
  [APPOINTMENT_TYPE_MODE.FIXED]: "Fixo",
  [APPOINTMENT_TYPE_MODE.CHOICE]: "Permitir escolha",
};

export const getAppointmentTypeOptions = () => [
  { value: APPOINTMENT_TYPE.ONLINE, label: APPOINTMENT_TYPE_LABELS[APPOINTMENT_TYPE.ONLINE] },
  { value: APPOINTMENT_TYPE.PRESENCIAL, label: APPOINTMENT_TYPE_LABELS[APPOINTMENT_TYPE.PRESENCIAL] },
];

export const getAppointmentTypeModeOptions = () => [
  { value: APPOINTMENT_TYPE_MODE.DISABLED, label: APPOINTMENT_TYPE_MODE_LABELS[APPOINTMENT_TYPE_MODE.DISABLED] },
  { value: APPOINTMENT_TYPE_MODE.FIXED, label: APPOINTMENT_TYPE_MODE_LABELS[APPOINTMENT_TYPE_MODE.FIXED] },
  { value: APPOINTMENT_TYPE_MODE.CHOICE, label: APPOINTMENT_TYPE_MODE_LABELS[APPOINTMENT_TYPE_MODE.CHOICE] },
];
